### ISSUE TITLE
eliane?

### ISSUE THREAD

**Issue by porres** [thormagnusson/threnoscopeSC#7]
not the best place to ask this I know but I also didn't know better

what is the 'eliane' sound source in threnoscope about? and where can I find this and more details about the other sound sources in the documentation?

thanks

**Comment by Etol1LC** [comment]
If I understand your question correctly,
\eliane Is a SuperCollider SynthDef, as any other "source" in ThrenoScope.

You can find It in DroneSynths.sc:

https://github.com/thormagnusson/threnoscopeSC/blob/master/DroneSynths.sc

Hope this answer your question. If not, please ask again.

Claudio Etol


Il mer 22 nov 2023, 02:49 porres ***@***.***> ha scritto:

**Comment by porres** [comment]
got it, a student of mine talked about this today and he claimed it was some stochastic technique waveform or something and we tried to check what it was during the class and we couldn't find it.
